import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  productItem: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    marginBottom: 10,
    borderRadius: 5,
    width: "90%",
    backgroundColor: "#edd7d5",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  serviceItem: {
    padding: 10,
    borderWidth: 1,
    borderColor: "#ccc",
    marginBottom: 10,
    borderRadius: 5,
    backgroundColor: "#e1edd5",
    width: "90%",
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  heading: {
    color: "white",
    width: "100%",
    backgroundColor: "brown",
    fontSize: 20,
    fontWeight: "bold",
    textAlign: "center",
    padding: 10,
    marginBottom: 10,
  },
  removeButton: {
    fontWeight: "bold",
    padding: 5,
    borderRadius: 60,
    borderWidth: 1,
    marginTop: 10,
  },
  Clearbutton: {
    backgroundColor: "red",
    width: "100%",
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    textAlign: "center",
    color: "white",
    fontWeight: "bold",
    fontSize: 12,
  },
  Submitbutton: {
    backgroundColor: "brown",
    width: "100%",
    padding: 10,
    borderRadius: 5,
    marginTop: 10,
    textAlign: "center",
    color: "white",
    fontWeight: "bold",
    fontSize: 12,
  },
  buttonView: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 20,
    padding: 10,
    width: "65%",
  },
  removeButtonText: {
    color: "black",
    fontWeight: "bold",
    fontSize: 20,
  },
});
